# Generated by Django 5.2.7 on 2025-10-08 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah_number', models.IntegerField()),
                ('ayah_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('translated_name', models.CharField(blank=True, max_length=250, null=True)),
                ('revelation_place', models.CharField(choices=[('makkah', 'Makkah'), ('madinah', 'Madinah')], max_length=10)),
                ('verses_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AyahPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='irab.ayah')),
            ],
        ),
        migrations.AddField(
            model_name='ayah',
            name='surah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='irab.surah'),
        ),
    ]
