# Generated by Django 5.2.7 on 2025-10-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surah',
            name='surah_id',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
