# Generated by Django 5.2.7 on 2025-10-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irab', '0002_surah_surah_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='surah',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
