# Generated by Django 5.2.7 on 2025-10-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irab', '0003_surah_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surah',
            name='slug',
        ),
    ]
