# Generated by Django 5.2.7 on 2025-10-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irab', '0004_remove_surah_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='surah',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
